// Generated by https://quicktype.io

import { ArticleInterface } from 'src/app/shared/types/article.interface';

export interface GetFeedResponseInterface {
  articles: ArticleInterface[];
  articlesCount: number;
}
